name: Time for new release

on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/check-time-for-new-release2.yml
  
jobs:
  check-time-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all tags
      
      - shell: pwsh
        id: needs-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # get latest release and the tag from it
          $release = gh api 'repos/{owner}/{repo}/releases/latest' | ConvertFrom-Json
          $tag = $release.tag_name
          
          # get the information from the last tag (assuming that is latest!)
          $info = git describe --tags
          $commitsSinceLastTag = $info.Split("-")[1]
          
          if ($commitsSinceLastTag -gt 0) {
            Write-Host "Found [$commitsSinceLastTag] commits since last tag, we should create a release"
            echo "newrelease=true" >> $env:GITHUB_OUTPUT
            echo "tag=$($info.Split("-")[0])" >> $env:GITHUB_OUTPUT
          }
          else {
            Write-Host "No changes since last tag, so nothing to release"
            echo "newrelease=false" >> $env:GITHUB_OUTPUT
          }
          
      # todo: 
      
      - name: Show output
        id: version
        if: steps.needs-release.outputs.newrelease == 'true'
        shell: pwsh
        run: |
          echo "A new release needs to be created" >> $env:GITHUB_STEP_SUMMARY
          echo "Current version: ["${{ steps.needs-release.outputs.tag }}"]" 
          $version = "${{ steps.needs-release.outputs.tag }}".Substring(1)
          echo "Converting tag to semver info: [$version]"
          echo "version=$version" >> $env:GITHUB_STEP_SUMMARY
      
      # if yes, call the api to create a new release
      # fetch new release tag first (sem ver? or do we need to check if we made breaking changes? Should not be breaking if all it is, are dependency updates?
      - name: Simple Semver
        id: semver
        if: steps.needs-release.outputs.newrelease == 'true'
        uses: matt-FFFFFF/simple-semver@v0.1.0
        with:
          semver-input: "${{ steps.version.outputs.version }}"
          increment: p

      - name: Use new semver
        run: echo "New tag= [${{ steps.semver.outputs.semver }}]"
