name: Time for new release2

on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/check-time-for-new-release2.yml
  
jobs:
  check-time-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all tags
          ref: main
      
      - shell: pwsh
        id: needs-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # get latest release and the tag from it
          $release = gh api 'repos/{owner}/{repo}/releases/latest' | ConvertFrom-Json
          $tag = $release.tag_name
          
          # get the information from the last tag (assuming that is latest!)
          $info = git describe --tags
          echo "Git describe info: [$info]"
          $commitsSinceLastTag = $info.Split("-")[1]
          
          if ($commitsSinceLastTag -gt 0) {
            echo "Found [$commitsSinceLastTag] commits since last tag, we should create a release"
            echo "newrelease=true" >> $env:GITHUB_OUTPUT
            $tag = $($info.Split("-"))[0]
            echo "Found tag [$tag]"
            echo "tag=$tag" >> $env:GITHUB_OUTPUT
            $version = $tag.Substring(1)
            echo "Converting tag to semver info: [$version]"
            echo "version=$version" >> $env:GITHUB_OUTPUT
          }
          else {
            echo "No changes since last tag, so nothing to release"
            echo "newrelease=false" >> $env:GITHUB_OUTPUT
          }
      
      - name: Show output
        if: steps.needs-release.outputs.newrelease == 'true'
        shell: pwsh
        run: |
          echo "A new release needs to be created" >> $env:GITHUB_STEP_SUMMARY
          echo "Current tag: [${{ steps.needs-release.outputs.tag }}]" 
          echo "Current version: [${{ steps.needs-release.outputs.version }}]" 
          
      # if yes, call the api to create a new release
      # fetch new release tag first (sem ver? or do we need to check if we made breaking changes? Should not be breaking if all it is, are dependency updates?
      - name: Simple Semver
        id: semver
        if: steps.needs-release.outputs.newrelease == 'true'
        uses: matt-FFFFFF/simple-semver@main #v0.1.0
        with:
          semver-input: "${{ steps.needs-release.outputs.version }}"
          increment: p

      - name: Use new semver
        run: |
          echo "New tag=[${{ steps.semver.outputs.semver }}]"
          echo "New tag=[${{ steps.semver.outputs.semver }}]" >> $env:GITHUB_OUTPUT
